config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'posts/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#delete'
  resources :posts, only: [:index, :new, :create]
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :token
  has_many :posts

  before_create :remember
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 65}, 
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

  #Returns a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.token = User.new_token
    self.remember_token = Digest::SHA1.hexdigest(token) #needs to be adjusted. if users already have remember_token should be changed to update_attribute
  end

  #Returns true if given token matches the digest
  def authenticated?(given_token)
    BCrypt::Password.new(remember_token).is_password?(given_token)
  end

  def forget
    update_attribute(:remember_token, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user
  #This logs the user in, giving them a temporary 
  #session and encrypting their user.id as the session[:user_id]
  def log_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  #This gives the user a new token, saving the digest to the database
  #It then adds that user's user.id to the permanent cookies and 
  #adds the new token to the permanent cookies
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      current_user=(user)
    else
      @current_user = nil
    end
  end

  def current_user=(user)
    if user && user.authenticated?(cookies[:remember_token])
      log_in user 
      @current_user = user
    end
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all
  end

  private

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      redirect_to posts_path
    else
      flash.now[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def delete
    sign_out if logged_in? 
    redirect_to login_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  </div>
<% if logged_in? %> 
  <div class="navbar-brand">
    <%= link_to "Log Out", logout_path, method: "delete" %>
  </div>
<% end %>
<%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <p>
    <%= f.label :title %> 
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %> 
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% if logged_in? %>
  <%= link_to "New Post", new_post_path %>
<% else %>
  <%= link_to "Sign in to view Authors", login_path %>
<% end %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Author</th>
    <th colspan="3"></th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
      <% if logged_in? %>
      <% author = User.find_by(id: post.user_id) %>
        <td><%= author.name %></td>
      <% end %>
    </tr>

    <% end %>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>